# CS231n Homework

### argmax

In [9]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)

print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[[0 1 2]
 [3 4 5]]
5
[1 1 1]
[2 2]
